### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'duck.duckffi_open')

### ISSUE THREAD

**Issue by kimmolinna** [evanwashere/duckdb#1]
When I updated bun to 0.5.1 I will get the following error message:
```js
TypeError: undefined is not an object (evaluating 'duck.duckffi_open')
      at open (/Users/linna/node_modules/@evan/duckdb/lib.mjs:122:6)
      at open (/Users/linna/node_modules/@evan/duckdb/index.mjs:4:22)
      at /Users/linna/duckdb-bun/test.js:4:11
```

**Comment by kimmolinna** [comment]
This is working after `bun upgrade --canary`
